[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_for_fee = "M5c95Zio3HQ1gvQ3pjhh8BsscrDcKnN28gxnQD1E17U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.28.0"
solana_version = "1.16.12"
